/**
  ******************************************************************************
  * @file    main.c
  * @brief   Main program for WM8960 Audio Player
  ******************************************************************************
  */

#include "main.h"
#include "i2c.h"
#include "i2s.h"
#include "dma.h"
#include "usart.h"
#include "gpio.h"
#include "wm8960.h"
#include "audio_player.h"

/* Private includes */
#include "string.h"

/* Private typedef */

/* Private define */
#define AUDIO_START_ADDRESS     44  /* WAV file header size */

/* Private macro */

/* Private variables */
extern I2C_HandleTypeDef hi2c1;
extern I2S_HandleTypeDef hi2s3;
extern DMA_HandleTypeDef hdma_spi3_tx;

/* Audio buffer */
uint16_t audio_buffer[AUDIO_BUFFER_SIZE];

/* WAV file data - Replace with your actual music data */
/* Format: 16-bit PCM, 48kHz, Stereo */
const uint16_t WaveData[] = {
    /* This is a placeholder. Replace with actual WAV data */
    0x0000, 0x0000, 0x0000, 0x0000,
};

uint32_t WaveDataLength = 0;
volatile uint32_t music_index = 0;

/* Private function prototypes */
void SystemClock_Config(void);
static void MPU_Config(void);

/* Private user code */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
    uint8_t res;
    
    /* MCU Configuration */
    
    /* MPU Configuration */
    MPU_Config();
    
    /* Enable I-Cache */
    SCB_EnableICache();
    
    /* Enable D-Cache */
    SCB_EnableDCache();
    
    /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
    HAL_Init();
    
    /* Configure the system clock */
    SystemClock_Config();
    
    /* Initialize all configured peripherals */
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_I2C1_Init();
    MX_I2S3_Init();
    MX_USART1_UART_Init();
    
    /* Initialize WM8960 */
    res = WM8960_Init(&hi2c1);
    if (res != 0)
    {
        printf("WM8960 Init Failed!\r\n");
        Error_Handler();
    }
    printf("WM8960 Init Success!\r\n");
    
    /* Set volume to 80% */
    WM8960_SetVolume(80);
    
    /* Calculate wave data length */
    WaveDataLength = sizeof(WaveData) / sizeof(WaveData[0]);
    
    /* Fill initial audio buffer */
    for (int i = 0; i < AUDIO_BUFFER_SIZE; i++)
    {
        if (music_index < WaveDataLength)
        {
            audio_buffer[i] = WaveData[music_index++];
        }
        else
        {
            audio_buffer[i] = 0;  /* Silence */
        }
    }
    
    /* Start I2S DMA transfer */
    HAL_I2S_Transmit_DMA(&hi2s3, audio_buffer, AUDIO_BUFFER_SIZE);
    
    printf("Audio Playback Started!\r\n");
    
    /* Infinite loop */
    while (1)
    {
        /* Main loop - can add other tasks here */
        HAL_Delay(100);
    }
}

/**
  * @brief  I2S DMA Half Transfer Complete Callback
  * @param  hi2s: I2S handle
  */
void HAL_I2S_TxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
{
    /* Fill first half of buffer */
    for (int i = 0; i < AUDIO_BUFFER_HALF; i++)
    {
        if (music_index < WaveDataLength)
        {
            audio_buffer[i] = WaveData[music_index++];
        }
        else
        {
            audio_buffer[i] = 0;
        }
    }
}

/**
  * @brief  I2S DMA Transfer Complete Callback
  * @param  hi2s: I2S handle
  */
void HAL_I2S_TxCpltCallback(I2S_HandleTypeDef *hi2s)
{
    /* Fill second half of buffer */
    for (int i = AUDIO_BUFFER_HALF; i < AUDIO_BUFFER_SIZE; i++)
    {
        if (music_index < WaveDataLength)
        {
            audio_buffer[i] = WaveData[music_index++];
        }
        else
        {
            audio_buffer[i] = 0;
        }
    }
}

/**
  * @brief  System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
    /* This is generated by CubeMX - keep your original configuration */
}

/**
  * @brief  MPU Configuration
  * @retval None
  */
static void MPU_Config(void)
{
    MPU_Region_InitTypeDef MPU_InitStruct = {0};
    
    /* Disable MPU */
    HAL_MPU_Disable();
    
    /* Configure MPU region for SDRAM or other memory if needed */
    
    /* Enable MPU */
    HAL_MPU_Enable(MPU_PRIVILEGED_DEFAULT);
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
    __disable_irq();
    while (1)
    {
        /* Error indicator - toggle LED or similar */
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
        HAL_Delay(200);
    }
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
    printf("Wrong parameters value: file %s on line %d\r\n", file, line);
}
#endif /* USE_FULL_ASSERT */

/**
  * @brief  Retargets printf to USART
  */
int __io_putchar(int ch)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, 0xFFFF);
    return ch;
}